version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - mongo

  redis:
    image: redis
    container_name: redis_server
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"