name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker
      run: docker-compose build

    - name: Run Containers
      run: docker-compose up -d

    - name: Wait
      run: sleep 10

    - name: Test API
      run: curl http://localhost:8000/docs